### ISSUE TITLE
Choose and download a library for running a json webserver and test that it works

### ISSUE THREAD

**Issue by lightvector** [lightvector/arimaa-server#14]

**Comment by lightvector** [comment]
I'm investigating Lift at the moment, reading through the docs and
compiling the example programs on a test machine. Their example html server
compiles and indeed when started it serves an index page through localhost.
I'll play with things myself soon to get a better understanding of how it
works.

**Comment by lightvector** [comment]
Settled on Scalatra, pushed a basic "hello-world" server setup along with the necessary libraries.

What's the best way to run and test a servlet?  I added a "package" command to the ant build file that builds a ".war" file at target/arimaa-server.war. I downloaded a jetty runner tool that I can use to run locally from there (I haven't pushed this yet), via: "java -jar jetty-runner-8.1.9.v20130131.jar target/arimaa-server.war", but it seems like there should be a better way. Do you have any knowledge about how this works?

Apologies for the mess about the username and email associated with the commit. Is it worth fixing? It's probably good if we could work out some system of review here so that I don't do something like that again. I don't know what best-practices are here - I'm still learning github.

**Comment by mattj256** [comment]
> Settled on Scalatra, pushed a basic "hello-world" server setup along with the necessary libraries.

Cool, now I have to figure out how to run it. :)

> Do you have any knowledge about how this works? [running Jetty with Ant]

I just did a quick Google search.  There's a plugin for Ant.  Let me know if you need help.  Let me know if you think we should be switching to sbt.
http://eclipse.org/jetty/documentation/current/ant-and-jetty.html#jetty-ant

> Apologies for the mess about the username and email associated with the commit

I'll forgive your mistakes if you forgive mine. ;)

> Is it worth fixing?

If it really bothers you you can check in two new commits: one that reverts d3b040 and a second that has the same changes as the original but with the correct username.  This will give you a chance to test out the review system. (See next point.)  

> It's probably good if we could work out some system of review

The "best practice" is that anything pushed to master should be treated as permanent.  (If you make a mistake, you resolve it by checking in a new commit that reverts the old one, not by removing that commit from the history.)

For you:
1. Create a branch off of master.  I use very uncreative names like "iss15" for work related to issue 15.  The best practice is that every pull request should reference an issue in the bug tracking system.  (If there's no appropriate issue, create one.)  My personal practice: "large" changes get an issue and a numbered branch.  If the change is just a few lines and isn't controversial or complicated, the branch gets a human-readable name and I don't bother putting it into the bug tracker.
2. When you're ready, submit a pull request to merge your branch into master.  Pull requests are visible to the public, so anyone can comment.
3. Once the request is approved there's some optional housekeeping that will make the history easier to read.  This is an advanced feature and not something you need to worry about right now.

For me:

My system is a little more complicated -- I make my changes in a separate repo, then request to merge my changes into your repo.  We already did that today so I don't think it needs further comment.
