### ISSUE TITLE
Use sbt to build the application.

### ISSUE THREAD

**Issue by mattj256** [lightvector/arimaa-server#16]
We might want to use sbt to build our server.
I don't see any compelling reason to set this up right now:
1. We don't have a lot of source files.
2. It's straightforward to change later on.
3. The online reviews of sbt are mixed.
4. Ant already does everything we need.

Also the learning curve is a bit too steep for me right now.

**Comment by lightvector** [comment]
Yes, I've seen disappointing reports in some cases about sbt's documentation or about certain cases involving needing flexibility.

Almost all of of the example projects I'm downloading for the various web frameworks use sbt or though. I think it's not too hard to make them work with Ant though. The primary difficulty is that sbt autodownloads all the dependencies for the various web frameworks, but it takes a bit of work to reverse-engineer what was downloaded and cached to figure out what those dependencies are to pull them into our project.

**Comment by mattj256** [comment]
At this point I'd rather spend my time hunting down Jar files than spend my time setting up a tool that I have limited confidence in.  (I've hunted down jars before - Maven's website lists the dependencies for every jar file.)  If sbt is the best tool for the job we should absolutely be using it.  Last week I had a really bad experience with a poorly-documented third-party library, so I want to avoid repeating that mistake.

**Comment by brendanator** [comment]
I actually made the code changes to implement this before I saw this discussion...

I think that adopting sbt is worth it even if there's a little steep learning curve to begin with. 
1. It solves the dependency issue that's mentioned above
2. It improves the compilation speed of Scala (once everything has been downloaded and compiled the first time)
3. It has some nice plugins to do common tasks. I've included [xbst-web-plugin](https://github.com/earldouglas/xsbt-web-plugin) which can build wars and run the application in jetty
4. I use it to do TDD. 
   - Load sbt 
   - Run the task `~testQuick`
   - Make code changes and save. Each time sbt will run any failing tests or tests affected by the code changes

Still, if you don't fancy it, that's fine too

**Comment by lightvector** [comment]
Thanks Brendan for taking a look and submitting this!

I will leave the decision about the build system up to Matt here when he
pops back in on Tuesday. I'm fine with going either way, so I think Matt is
the one for whom this decision might make the most difference, given his
current experience of the learning curve involved with Scala and other
preferences he may have.

**Comment by mattj256** [comment]
Ok I checked out Brendan's branch and ran the server with sbt.
Everything works, and if a novice like me can get it to work on the first try it can't be all bad.
Thanks for leaving this up to me.  I'm going to merge this and I apologize in advance for any beginner questions I may ask.  Brendan thanks for setting this up!
