### ISSUE TITLE
Auto-check XML indenting

### ISSUE THREAD

**Issue by mattj256** [lightvector/arimaa-server#17]
It looks like Checkstyle has support for this:
https://groups.google.com/forum/#!topic/checkstyle/WG6KBm9i8t4

I'm not sure if ScalaStyle does.

**Comment by lightvector** [comment]
Do we have XML files to be checked?

**Comment by mattj256** [comment]
- src/main/resources/logback.xml
- web.xml
- scalastyle-config.xml

I creating this issue thinking I would (maybe) do it at some point.  I'm never going to implement this.  This is only important if you think it's important.

**Comment by lightvector** [comment]
I'm declaring this not particularly important. Thanks!
