### ISSUE TITLE
Add ScalaStyle

### ISSUE THREAD

**Issue by mattj256** [lightvector/arimaa-server#26]
Add ScalaStyle target for sbt.

> Scalastyle examines your Scala code and indicates potential problems with it. If you have come across Checkstyle for Java, then you’ll have a good idea what scalastyle is. Except that it’s for Scala obviously.

http://www.scalastyle.org/sbt.html

Once you add the sbt plugin you can do:

> sbt scalastyleGenerateConfig
> sbt scalastyle

Overview of SBT plugin: http://www.scalastyle.org/sbt.html
XML file configuration options: http://www.scalastyle.org/configuration.html
Example config file.  (Used by ScalaStyle team, and Martin Odersky): http://www.scalastyle.org/scalastyle_config.xml
List of all implemented rules: http://www.scalastyle.org/rules-0.2.0.html

**Comment by lightvector** [comment]
@mattj256 - Feel free to close if you think this is good.
