### ISSUE TITLE
Decide on top-level package structure

### ISSUE THREAD

**Issue by mattj256** [lightvector/arimaa-server#3]
The current package structure (namespace) is not intended to be permanent.
We should decide whether we will be under arimaa.com or some other domain name, then change the package to match.

Options:
- arimaa.com (Requires Omar's permission and maybe permission of the community.)
- playarimaa.com / playarimaa.net / playarimaa.org (These domain names are available.  Requires Omar's permission because he owns the trademark.)
- arimaa.club (This is rabbits' domain name?)
- Something without "arimaa" in it.

**Comment by lightvector** [comment]
Decided on "playarimaa.org", and "org.playarimaa.server". Wooo!
