### ISSUE TITLE
Hash conflict when downloading paranamer-2.7 library

### ISSUE THREAD

**Issue by lightvector** [lightvector/arimaa-server#34]
The following error occurs in sbt when trying to download a library that is depended on by the json parsing libraries we use:

[warn] problem while downloading module descriptor:
https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.7/paranamer-2.7.pom:
invalid sha1: expected=deea673ac6c495cfca3c2fecce26bd9b67295e5b computed=36ef984e4403f800d8aeb5b82045ea4cec0db07b

(libraries added with this revision):
b1c87a90536ac4e2bf01d0292bbb0530e6d19808

For now, the following line in Build.scala disables checksum checking. 
checksums in update := Nil

Once the mismatching checksum issue is fixed in the library, we should remove this line and retest.

**Comment by lightvector** [comment]
Actually, I'm not getting this error any more, even when I remove this line, blow away my ~/.ivy2 cache of libraries downloaded by sbt, and have them all redownloaded again, so I'm assuming this was fixed or this error was somehow transient.

**Comment by mattj256** [comment]
I did a Google search for the hash code and it came up empty, so it might have been a configuration error or a transient problem that got fixed.
