### ISSUE TITLE
Replace org.playarimaa.util.Result with scala.util.Try

### ISSUE THREAD

**Issue by mattj256** [lightvector/arimaa-server#38]
Scala has a built-in monadic class scala.util.Try.
It is a case class and the types are Success or Failure.
(I hope I'm getting the terminology right!)

This class integrates with Scala's exception handling.  (If an exception is thrown it returns Failure and a message, otherwise Success.)

**Comment by lightvector** [comment]
Hooray! Built-in library types to the rescue. :)
