### ISSUE TITLE
Message lengths, rate limiting

### ISSUE THREAD

**Issue by lightvector** [lightvector/arimaa-server#40]
Eventually, before we actually go live, we probably want to consider adding limits on message size and rate for things like sending of chat messages, opening of new games, etc.

**Comment by mattj256** [comment]
Some things to think about:
1. Limit on number of open games at the same time. (Players haven't been paired up yet)
2. Limit on number of active games at the same time.  (Aggregate for the whole server.)
3. Limit on number of active games per player. (Max number of simultaneous games that a player can play at the same time.)
4. Limit on maximum number of players logged in at the same time.

Freechess.org has an arbitrary threshold for message rate.  If you go over that rate you are limited to one chat message per 5 seconds until the cooldown period expires.  It's possible to have escalating levels here: if they violate the rate limits, then the cooldown expires, then they violate the rate limits again, it's reasonable to have a stiffer penalty.  If someone repeatedly violates message rate limits it would be nice to trip an alarm so any admins on duty can respond to it.

**Comment by lightvector** [comment]
I've implemented 1-3 but not 4. Do you think 4 is particularly important?

Also implemented now are limits on changes and rates, rather than just limits on the size of the current state. Including:
- Login attempt rate per username
- Registration rate per-IP
- Account-related queries per-IP
- Game creation rate per username
- Chat message rate and character volume per username

Given that, I'm pretty happy with things at the moment - do you think this issue can be considered handled?

**Comment by mattj256** [comment]
I think this is totally ready for production, and you can close it out if you want.

I do have some other suggestions, for when/if you have time.

I think 4 is certainly important, but no reason that needs to be handled right away.  Longer-term I think it would be good to have a limit on the number of users and/or enough server monitoring that we know how stressed the server is before it has problems.

I think the login rate could use some tweaking.  My recommendation: no delay, but after X consecutive failed login attempts the user is locked out and has to wait 30-60 minutes or contact an admin.  If you want to be really fancy throw up a CAPTCHA after the first one or two failed login attempts.  Again, this is in no way urgent.  I would say it's much more important to log failed login attempts and especially repeated failed login attempts.

**Comment by lightvector** [comment]
Too many attempts produces a line in the server logs. It's not really
proper monitoring, but at least that's at least something.

I don't understand what you mean by delay. Currently what's implemented is
something like each username having X login attempts max at any given time,
which replenish at a rate of Y per minute, for some value of X and Y (I
forget exactly). This was the simplest possible scheme to implement I could
think of - the only piece of state is a float and all it does when you have
no attempts left is reject and log the event.

**Comment by mattj256** [comment]
Sounds perfect.
You can close this out unless you're waiting for someone or something else.

**Comment by lightvector** [comment]
Okay!
