### ISSUE TITLE
Memory leak in when testing webserver

### ISSUE THREAD

**Issue by lightvector** [lightvector/arimaa-server#49]
There's a memory leak in when running SBT to test the webserver. Enough runs of ChatTests.scala will result in something like the following:

Exception in thread "Thread-32"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-32"

OR

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: PermGen space

As far as I can tell, this is because the web server infrastructure leaks in Java's permanent generation memory on multiple runs. Using "jmap" to probe the memory usage of java, it seems like every run of the tests consumes about 20-40 MB more memory in the permanent generation that is then never freed. 

I also haven't find any online resources explaining how to fix it. I only find resources that explain how to increase the limit (and thereby require less frequent restarts of sbt).

**Comment by mattj256** [comment]
Is this useful?
http://stackoverflow.com/a/1451668
(Read the whole answer - the part at the end looks like the most important.)

If not useful please clarify (if you know) -- which library/framework is this? Scalatra?  Jetty?  I have a hard time keeping this stuff straight in my head.

**Comment by lightvector** [comment]
We're using Scalatra. I believe it compiles into a servlet (which in packaged form, this is a .war file) that can then be run using servlet-running things, like is built-in to sbt, or like jetty.

Yes, I tried the things mentioned in that post for locally configuring sbt. They help, in that they defer the problem (particularly setting -XX:MaxPermSize to a bigger number, at 512MB you get about 20 runs before you run out of memory), but still the memory leak exists.

**Comment by mattj256** [comment]
How about this one?
http://stackoverflow.com/a/3334954

Yes, increasing MaxPermSize is a band-aid: it may defer the problem but it doesn't address the underlying cause.  The default behavior of the JVM garbage collector is fine for Java but it doesn't work for a language like Scala that has tons of dynamically-generated classes.

I'm surprised there isn't more information about this online, or better support for this use case.  It's not like we're the only people in the whole world using Scala to run a production server.

**Comment by lightvector** [comment]
I haven't tried the thing mentioned in that one. I'll try it when I get back around to it - it may indeed be the case that memory isn't truly leaked (in the sense of being held on to by a reference somewhere) and can still be collected with appropriate GC configuration.

**Comment by lightvector** [comment]
Adding UseConcMarkSweepGC, everything seems okay now. The memory usage tops out and doesn't grow unboundedly.
