### ISSUE TITLE
Allow either player to abort the game before the first move has been played

### ISSUE THREAD

**Issue by mattj256** [lightvector/arimaa-server#57]
Allow either player to abort the game before the first move has been played, with no ratings penalty.

(There is some potential for abuse here, so that should be either monitored automatically, or else players should have a way to report abuse to the admin staff.)

(I believe the Free Internet Chess Server allows either player to abort without penalty, i.e. first white moves, then black has the option of aborting with no penalty rather than continuing the game.  Again, there's potential for abuse here and that has to be managed in some way.)

**Comment by lightvector** [comment]
This is implemented. Game win/loss statistics and ratings are only updated for a player if that player made at least one move in that game.
