### ISSUE TITLE
Decide on software license.

### ISSUE THREAD

**Issue by mattj256** [lightvector/arimaa-server#7]
Neither mattj256 nor lightvector have strong feelings on this one.
Lightvector is going to talk to Omar and/or the community.

**Comment by lightvector** [comment]
Still talking to Omar about this. The back-and-forth is quite slow, with long delays between responses, but I'll keep at it.

**Comment by egaga** [comment]
What's the current status? License being undefined, having a repository publicly accessible has little meaning (at least for me).

**Comment by lightvector** [comment]
Thanks for the reminder - I forgot about this open issue and haven't done anything with it. I will contact Omar and get it resolved as soon as I can. If I don't hear back in a reasonable amount of time I think I will go ahead with the plan described below:

@mattj256, @aaronyzhou  - both of you being contributors to this project, do either of you object to to a BSD-style license or the plan below? 

The plan would be to add a "new BSD" license - https://opensource.org/licenses/BSD-3-Clause. This license would cover everything in this repo EXCEPT for the piece and board images. Additionally, it would NOT cover the usage of the code for Arimaa-related purposes (in particular, spinning up an independent public copy of the site) or the usage of the graphics, as Omar continues to own the Arimaa game and graphics and as its owner retains the rights to its licensing for both commercial and noncommercial use. A user wanting to spin up their version of the site/software, if it were also Arimaa related (as opposed to, say, using parts of the code for something else unrelated to Arimaa), would need to contact Omar at arimaa.com for permission. Which in practice is basically the case anyways.

So we would have a license file with the BSD-style license, but preceded by something like the following text:

---

The source code, files, and other resources in this repository, EXCEPT FOR the Arimaa-related board and piece graphics (in [insert path to board and piece graphics here]), are freely provided for use under a BSD-style license, the text of which is below.

HOWEVER, please note that the rights granted under this license DO NOT extend to the Arimaa game itself OR to any commercial or non-commercial usage involving the Arimaa game (such as running a copy of this website) OR to the Arimaa-related board and piece graphics included in this repository. 

Any user of the contents of this repository or of any derivative work based on it, if such usage involves the Arimaa game or the Arimaa name or the Arimaa piece and board graphics in any way, is responsible for ensuring that the usage complies with the Arimaa Public License (http://arimaa.com/arimaa/license/current.txt) and is responsible for obtaining any necessary authorization or license by contacting Arimaa.com. The Arimaa name is a trademark of Arimaa.com. The Arimaa game is patented. The Arimaa game rules, the Arimaa board design, and the Arimaa piece design are copyright protected.

---

(Note that some of the wording in the final paragraph is chosen to match the wording that Omar has typically requested/required for past projects he has okayed).

Any thoughts, comments, or objections?

**Comment by mattj256** [comment]
@lightvector The main thing is that the software should have an explicit license.  (Which is why I created this issue in the first place.) I would prefer a license that's as permissive as possible (like BSD), so commercial use isn't excluded.  Like you said, if someone wants to spin up a commercial server they still have to contact Omar anyway.  I definitely don't want to be responsible for talking to lawyers or chasing down Omar, and I don't want to be a roadblock for any of that.  My perspective is just talk to Omar and do what you think is best.

Also, maybe you could ask Omar to sell or transfer the patent and license to someone else, or to a group constructed for that purpose?  I'm too much of a troublemaker to own the patent.  I think you'd be a great steward of the game, and I can think of at least half a dozen others who have been involved in the community for years who would be great stewards as well.

**Comment by lightvector** [comment]
Agreed. I heard back from Omar! He has confirmed that he is okay with this plan if it has a notice like the one I described, (and also that the image graphics themselves are actually public domain, so we can simplify that part of things). So now we're just waiting on @aaronyzhou, who I do want to confirm with because he is the author of a large amount of the frontend code. I sent him a separate email privately as well in case he doesn't get or filters out github-related emails.

**Comment by lightvector** [comment]
Okay heard back from Aaron. Proceeding!

**Comment by mattj256** [comment]
Yay!  I'm glad this is finally closed!
